# docker-compose.yml

version: "3.8"

services:
    authors-service:
        # build: ./app
        image: cfeliot/app-author_py:1
        volumes:
            - .:/app
        environment:
            - DATABASE_URL=postgresql://postgres:postgres@db:5432/distribuida
            - SERVER_PORT=8080
        depends_on:
            - db
        labels:
            - "traefik.http.routers.authors.rule=PathPrefix(`/app2`)"
            - "traefik.http.middlewares.authors.stripprefix.prefixes=/app2"
            - "traefik.http.routers.authors.middlewares=authors"
        expose:
            - 8080
    db:
        image: arm64v8/postgres
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        expose:
            - 5432
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=distribuida
    proxy:
        image: traefik:v2.9.6
        command: --api.insecure=true --providers.docker
        ports:
            - "80:80"
            - "8080:8080"
        expose:
            - 80
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
    tracing:
        image: jaegertracing/all-in-one
        ports:
            - "16686:16686"
            - "14250:14250"
volumes:
    postgres_data:
